package com.challenge.api.model;

import java.time.Instant;

/**
 * Data accepted by the create-employee endpoint.
 *
 * <p>The request deliberately leaves out {@code uuid} and {@code fullName}; those values are generated by the
 * application instead of being trusted from the caller.
 */
public record EmployeeRequest(
        String firstName,
        String lastName,
        Integer salary,
        Integer age,
        String jobTitle,
        String email,
        Instant contractHireDate,
        Instant contractTerminationDate) {}
